version: '3.8'

services:
  bitcoind:
    image: ruimarinho/bitcoin-core
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - ./bitcoin-data:/home/bitcoin/.bitcoin
    command:
      -printtoconsole

  cpp-daemon:
    build:
      context: .
      dockerfile: Dockerfile.cpp
    depends_on:
      - bitcoind
    restart: unless-stopped

  python-controller:
    build:
      context: ./python-controller
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "50051:50051"
    depends_on:
      - cpp-daemon
      - influxdb
    restart: unless-stopped

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - INFLUXDB_DB=blockchain_anomalies
    volumes:
      - influxdb:/var/lib/influxdb
    restart: unless-stopped

  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - ./logs:/log
    restart: unless-stopped

volumes:
  influxdb: