# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12grpc_service.proto\x12\nblockchain\"E\n\tSignature\x12\t\n\x01r\x18\x01 \x01(\t\x12\t\n\x01s\x18\x02 \x01(\t\x12\x14\n\x0c\x62lock_height\x18\x03 \x01(\x04\x12\x0c\n\x04txid\x18\x04 \x01(\t\"l\n\x07\x41nomaly\x12(\n\tsignature\x18\x01 \x01(\x0b\x32\x15.blockchain.Signature\x12\x11\n\tentropy_r\x18\x02 \x01(\x01\x12\x11\n\tentropy_s\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"3\n\x0f\x41nomalyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2U\n\x0e\x41nomalyService\x12\x43\n\rReportAnomaly\x12\x13.blockchain.Anomaly\x1a\x1b.blockchain.AnomalyResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNATURE']._serialized_start=34
  _globals['_SIGNATURE']._serialized_end=103
  _globals['_ANOMALY']._serialized_start=105
  _globals['_ANOMALY']._serialized_end=213
  _globals['_ANOMALYRESPONSE']._serialized_start=215
  _globals['_ANOMALYRESPONSE']._serialized_end=266
  _globals['_ANOMALYSERVICE']._serialized_start=268
  _globals['_ANOMALYSERVICE']._serialized_end=353
# @@protoc_insertion_point(module_scope)
